CREATE TABLE "audit_fields" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "user_app_settings" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "subscription_plans" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	"name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE "user_subscription" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"order" BIGINT,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "order" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"user" BIGINT NOT NULL,
	"amount" MONEY NOT NULL,
	"order_status" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "investment_institutions" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "investment_institutions" IS 'e.g., Groww, Zerodha, SBI, etc.';


CREATE TABLE "investment_type" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "investment_type" IS 'Table for SIP, FD, PPF, NPS, Stocks, Mutual Fund';


CREATE TABLE "investment" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"user" BIGINT NOT NULL,
	"recurring" BOOLEAN NOT NULL,
	"institution" BIGINT,
	"name" VARCHAR(255),
	"type" BIGINT NOT NULL,
	"amount" MONEY NOT NULL,
	"sip_end_date" DATE,
	"sip_start_date" DATE,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "expense_category" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "budget" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"user" BIGINT NOT NULL,
	"name" VARCHAR(255),
	"month" VARCHAR(255) NOT NULL,
	"category" BIGINT NOT NULL,
	"amount" MONEY NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "address" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"line1" VARCHAR(255) NOT NULL,
	"line2" VARCHAR(255),
	"line3" VARCHAR(255),
	"city" BIGINT NOT NULL,
	"pincode" VARCHAR(255) NOT NULL,
	"latitude" DECIMAL,
	"longitude" DECIMAL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "city" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"state" BIGINT NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "state" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"country" BIGINT NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "country" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "bank" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"IFSC_prefix" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "bank_branch" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"bank" BIGINT NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"ifsc_code" VARCHAR(255) NOT NULL,
	"micr_code" VARCHAR(255),
	"address" BIGINT NOT NULL,
	"contact_no" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "bank_address" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"line1" VARCHAR(255) NOT NULL,
	"line2" VARCHAR(255),
	"line3" VARCHAR(255),
	"city" BIGINT NOT NULL,
	"pincode" VARCHAR(255) NOT NULL,
	"latitude" DECIMAL,
	"longitude" DECIMAL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	"original_city_name" VARCHAR(255),
	"original_state_name" VARCHAR(255),
	"original_country_name" VARCHAR(255),
	PRIMARY KEY("id")
);




CREATE TABLE "account_type" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"description" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "account" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"type" BIGINT NOT NULL,
	"bank" BIGINT NOT NULL,
	"account_no" VARCHAR(255),
	"balance" MONEY,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "provider" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "payment_methods" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255),
	"provider" BIGINT NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "income" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"user" BIGINT NOT NULL,
	"name" VARCHAR(255),
	"source" BIGINT NOT NULL,
	"income" MONEY NOT NULL,
	"account" BIGINT,
	"payment_method" BIGINT,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "income_source" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "expense" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"category" BIGINT NOT NULL,
	"user" BIGINT NOT NULL,
	"name" VARCHAR(255) NOT NULL,
	"expense" MONEY NOT NULL,
	"recurring" BOOLEAN NOT NULL,
	"notes" VARCHAR(255),
	"account" BIGINT,
	"payment_method" BIGINT,
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);




CREATE TABLE "user" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"code" UUID NOT NULL,
	"firstname" VARCHAR(255) NOT NULL,
	"lastname" VARCHAR(255),
	"display_name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL,
	"phone" VARCHAR(255) NOT NULL,
	"timezone" TIMETZ,
	"currency" VARCHAR(255),
	"is_active" BOOLEAN NOT NULL,
	"created_by" BIGINT,
	"created_on" DATE,
	"updated_by" BIGINT,
	"updated_on" DATE,
	"deleted_by" BIGINT,
	"deleted_on" DATE,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "user" IS 'This is our main user table';

ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "income"("user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "expense"("user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "provider"
ADD FOREIGN KEY("id") REFERENCES "payment_methods"("provider")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account"
ADD FOREIGN KEY("type") REFERENCES "account_type"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bank"
ADD FOREIGN KEY("id") REFERENCES "bank_branch"("bank")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bank_address"
ADD FOREIGN KEY("id") REFERENCES "bank_branch"("address")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "country"
ADD FOREIGN KEY("id") REFERENCES "state"("country")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "state"
ADD FOREIGN KEY("id") REFERENCES "city"("state")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "city"
ADD FOREIGN KEY("id") REFERENCES "address"("city")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bank_branch"
ADD FOREIGN KEY("id") REFERENCES "account"("bank")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "city"
ADD FOREIGN KEY("id") REFERENCES "bank_address"("city")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "payment_methods"
ADD FOREIGN KEY("id") REFERENCES "income"("payment_method")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "account"
ADD FOREIGN KEY("id") REFERENCES "income"("account")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "income"
ADD FOREIGN KEY("source") REFERENCES "income_source"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "expense"
ADD FOREIGN KEY("account") REFERENCES "account"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "expense"
ADD FOREIGN KEY("payment_method") REFERENCES "payment_methods"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "investment_type"
ADD FOREIGN KEY("id") REFERENCES "investment"("type")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "investment"("user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "investment_institutions"
ADD FOREIGN KEY("id") REFERENCES "investment"("institution")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "budget"("user")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "expense_category"
ADD FOREIGN KEY("id") REFERENCES "budget"("category")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "expense_category"
ADD FOREIGN KEY("id") REFERENCES "expense"("category")
ON UPDATE NO ACTION ON DELETE NO ACTION;