packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  next: '15.5.9'
  react: ^19.2.3
  react-dom: ^19.2.3

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tmp@<=0.2.3: '>=0.2.4'
