packages:
  - apps/*
  - packages/*

catalog:
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  next: ^15.4.8
  react: ^19.1.2
  react-dom: ^19.1.2

overrides:
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  tmp@<=0.2.3: '>=0.2.4'
